version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - 'app-gems:/usr/local/bundle/gems'
    env_file: .env
    environment:
      RAILS_ENV: '${RAILS_ENV}'
    command: '/bin/bash -c  "rm -f /app/tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"'

  database:
    image: 'postgres:15.2'
    env_file: .env
    environment:
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_DB: '${DATABASE_NAME}'
    ports:
      - '5432:5432'
    volumes:
      - 'app-postgres:/var/lib/postgresql/data'

volumes:
  app-gems:
  app-postgres:
